### PR TITLE
FD-0091(docs)-Adds-contibutormd

### PR DESCRIPTION
**Pull request by SincerelyBrittany**

### CODE REVIEW

**Review by stef-codes — CHANGES_REQUESTED** [review]
Thanks for adding this!  You have linters that aren't in the existing package.json file. 

It shouldn't be a problem as they should be added too. It would be better if you separated the two files to submit for pull requests. It helps with the separation of concerns.

@Sydnee510 @lanicemp

**Comment by SincerelyBrittany** [comment]
> Thanks for adding this! You have linters that aren't in the existing package.json file.
> 
> It shouldn't be a problem as they should be added too. It would be better if you separated the two files to submit for pull requests. It helps with the separation of concerns.
> 
> @Sydnee510 @lanicemp

Will do, but how does the contributor.md look? @stef-codes

**Review by lanicemp — APPROVED** [review]
gtg

**Review by Sydnee510 — APPROVED** [review]
QA/+1

**Review by stef-codes — APPROVED** [review]

**Comment by stef-codes** [comment]
Thanks for making those changes!

**Pull request merged**
