### PR TITLE
FD-#7-feat:Routes added

### PR DESCRIPTION
**Pull request by anujverma-eng**
Hi There,
I've added the Recommended Routes,
additionally, I've added NotFound Routes as well.

## **Dependencies Used:**

image

## **App.js will look like**

image

## **I've used Index.js in Pages to export & then import components**

image
image

### CODE REVIEW

**Comment by anujverma-eng** [comment]
Hi, @Sydnee510 
If it is Resolved, can we close this PR.

**Comment by SincerelyBrittany** [comment]
Hi @anujverma-eng, I know this was not mentioned in the criteria but would you mind adding a line for the AboutUs, ContactUs, and JoinUs. That will allow http://localhost:3000/aboutus and http://localhost:3000/about-us to work. 

So pretty much update:

```
        <Route exact path='/about-us' element={<AboutUs/>} />
        <Route exact path='/contact-us' element={<ContactUs/>} />
        <Route exact path='/join-us' element={<JoinUs/>} />
```

to something like this for each route with a dash: 

`   {['aboutus', 'about-us' ].map(path => <Route path={path} element={<AboutUs/>} />)}`

Also (@lanicemp and @Sydnee510) do we want the route to be an exact route for all of them?

**Review by SincerelyBrittany — CHANGES_REQUESTED** [review]
Please add 
`{['aboutus', 'about-us', 'widgets'].map(path => <Route path={path} element={<AboutUs/>} />)}`

For about-us, join-us, and contact-us

**Comment by SincerelyBrittany** [comment]
Also @anujverma-eng , if you wouldn't mind adding test https://testing-library.com/docs/example-react-router/

**Comment by anujverma-eng** [comment]
> Please add `{['aboutus', 'about-us', 'widgets'].map(path => <Route path={path} element={<AboutUs/>} />)}`
> 
> For about-us, join-us, and contact-us

Yes, Sure
@SincerelyBrittany 
can you pls tell me, what is the 'widgets' in this array [do you want to include them in the path for aboutUS? or it is anything else]

**Review by SincerelyBrittany — DISMISSED** [review]

**Comment by Sydnee510** [comment]
@anujverma-eng can we get you to resolve the merge conflicts before we approve

**Review by KiloWattDot — APPROVED** [review]
QA/+1

**Pull request merged**
