### PR TITLE
FD-#11-test-RoutesTesting

### PR DESCRIPTION
**Pull request by anujverma-eng**
Hi @all, I've added the Unit Testing for all Routes, below are the Pass Test Cases. #21 

## Merge Flow
First --> #17 
Then --> this PR

image

image

[Analogy Used](https://dev.to/bonnie/testing-react-apps-that-use-react-router-2bmd)

### CODE REVIEW

**Review by SincerelyBrittany — DISMISSED** [review]
Thank you

**Review by Sydnee510 — APPROVED** [review]
QA/+1

**Comment by Sydnee510** [comment]
hey @anujverma-eng can you resolve merge conflicts so we can approve

**Review by SincerelyBrittany — APPROVED** [review]

**Review by Sydnee510 — APPROVED** [review]
+1

**Pull request merged**
