### PR TITLE
Fd 999 final styling

### PR DESCRIPTION
**Pull request by mariorojasac**
- [x] The founder's card
- [x] The featured member's section

Update spacing:

- [x] spacing between social icons 
- [x] spacing between featured member cards
- [x] spacing under featured members title
- [x] spacing above the featured members title and below the mission statement

Update card assets:

- [x] update all featured members social links/icons
- [x] update featured members emails

Update mission statement:

- [x] Align paragraph ```left``` like the who are we/about us statement
- [x] should we leave mission title centered?

Update Founding team's cards:

- [x] align paragraphs/bios ```left``` 
- [x] leave the names and titles centered?``

### CODE REVIEW

**Review by Clue355 — DISMISSED** [review]
QA/+1

**Review by Sydnee510 — CHANGES_REQUESTED** [review]
Hey @mariorojasac the mission statement looks a little weird to me... what do you think? should we add a black background like all the other about us statements? Or do something to make it blend in with the rest of the page.
Also, The spacing on the member cards looks a little weird too with the emails... I wonder if we should take off the emails...

**Comment by StashaG** [comment]
> Hey @mariorojasac the mission statement looks a little weird to me... what do you think? should we add a black background like all the other about us statements? Or do something to make it blend in with the rest of the page. Also, The spacing on the featured member cards looks a little weird too with the emails... I wonder if we should take off the emails...

I agree I think adding a black background to the Mission statement would make it look better because it will match the about us section. What about adding an email icon that would open up an email window to whatever default email account you have? Also, what about changing the "Y" icon to a github icon to make it universal? I wasn't sure where that icon was going to take me until I hovered over it.

**Review by Clue355 — DISMISSED** [review]
QA/+1

**Review by Sydnee510 — APPROVED** [review]
QA/+1

**Review by StashaG — APPROVED** [review]
+1

**Pull request merged**
