### PR TITLE
FD-005.3 Member card component #112

### PR DESCRIPTION
**Pull request by ZeeMonk-pixel**
## Fixes

Fixes 
Issue Title: FD-005 - 
Github #[112]
Created by @[Clue355]

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`development`)
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

Release Notes
-------------

Decisions
---------

Technical Details
-----------------

Links
-----

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by KiloWattDot** [comment]
I'm adding this screenshot for reference  so we can see where you are at without having to navigate to your branch but nicejob! Are you finished or need some guidance?
@ZeeMonk-pixel 

member card - monkg

**Comment by ZeeMonk-pixel** [comment]
> I'm adding this screenshot for reference so we can see where you are at without having to navigate to your branch but nicejob! Are you finished or need some guidance? @ZeeMonk-pixel
> 
> member card - monkg

Yes I am done with the issue... since it's only the card component, that's what I have there. It's static information now till the members data are available for fetching then we can replace it with the data. But for now, I'm done with the card component UI... or is there anything else you'll love me to add?

**Comment by Sydnee510** [comment]
Hey @ZeeMonk-pixel we have made updates to the dev branch where we have set up the fetch request and the search functionality for the members. Can you update your member cards to reflect the data getting fetched from the API. Also please adjust your card sizing and the page sizing/white space. Let us know in discord if you need any help. 

To test the API you must run the backend application locally or on gitpod, then seed the database with the seed data by running rails db:seed and then pasting the URL endpoint into the fetch request.

**Comment by ZeeMonk-pixel** [comment]
> Hey @ZeeMonk-pixel we have made updates to the dev branch where we have set up the fetch request and the search functionality for the members. Can you update your member cards to reflect the data getting fetched from the API. Also please adjust your card sizing and the page sizing/white space. Let us know in discord if you need any help.
> 
> To test the API you must run the backend application locally or on gitpod, then seed the database with the seed data by running rails db:seed and then pasting the URL endpoint into the fetch request.

Yes I can… I will get to work on it starting Saturday.

**Pull request closed without merging**
