### PR TITLE
Fd 008.1_loginpage

### LINKED ISSUE #116: FD-008.1 Create Login Page
Build out the login form for the login page
The `login with google` URL and Icon will allow users to sign in with google once omni auth is set up (for now just use the text and icon as the placeholder)
The `sign up to join YNA - apply here ` URL will take users to the member application on the Join page (we can go ahead and set the URL end point to the current Join page)

Use figma designs as a refererence 
Screen Shot 2023-07-28 at 10 32 04 PM

### PR DESCRIPTION
**Pull request by KiloWattDot**
## Fixes

Fixes 
Issue Title: FD-008.1-LoginPage- 

Created by @KiloWattDot 

## Description
- Page/Styling Done
- Page is responsive 
_- Google Sign in needs to be added and Linking the apply here button._

login page

-->

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`development`)
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

Release Notes
-------------

Decisions
---------

Technical Details
-----------------

Links
-----

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Sydnee510** [comment]
Hey @KiloWattDot I dont see the login button in the navbar... can you add it?

**Comment by KiloWattDot** [comment]
Just added the login button.

**Review by Sydnee510 — DISMISSED** [review]
QA/+1

**Review by Clue355 — CHANGES_REQUESTED** [review]
The input boxes for email and password should be rounded like in the figma and should not have a yellow border. Also, the dimensions look a bit big so make it smaller. I'll adjust the sizes in figma

**Comment by KiloWattDot** [comment]
Made the changes.

**Review by Clue355 — COMMENTED** [review]
QA / +1

**Review by Clue355 — APPROVED** [review]

**Review by Sydnee510 — APPROVED** [review]
QA/+1

**Pull request merged**
