### PR TITLE
FD-007.3 member app styling

### LINKED ISSUE #117: FD-007.3 Customize styling member app google form
**We will be keeping our current google form instead of building a new form to store our user data. The current google member form will be used for our users to sign up to be on our app. Now we want to customize the styling to match our theme**

Since we have embedded the Google Form in our website and want to customize the CSS to match the theme of our website, we can achieve this by applying custom CSS styles to the elements of the embedded form. Here's how we can do it:

Step 1: Identify the Google Form Elements

Inspect the elements of the embedded Google Form using your browser's developer tools. This will help you identify the HTML structure and classes used by the form elements. You can right-click on the form fields and choose "Inspect" or "Inspect Element" to open the developer tools.

Step 2: Create Custom CSS

In your website's CSS file, you can create custom CSS rules to target and style the specific form elements you identified in Step 1. You can override the default styles provided by Google Forms with your own styles to match your website's theme.

For example, let's say your embedded Google Form has a text input field with the class "entry-field". You can style it with the following custom CSS:

```css
/* Example custom CSS to style the text input field */
.entry-field {
  background-color: #f5f5f5; /* Change the background color */
  border: 1px solid #ccc; /* Change the border */
  padding: 10px; /* Add padding */
  color: #333; /* Change the text color */
  font-size: 14px; /* Change the font size */
  /* Add any other styles you want to customize */
}
```

You can apply similar custom CSS rules to other form elements like checkboxes, radio buttons, select dropdowns, etc., to style them according to your website's theme.

Step 3: Include Custom CSS in Your Website

Make sure to include your custom CSS file in your website's HTML. You can link the CSS file in the `<head>` section of your website's HTML code:

```html
<head>
  <!-- Other meta tags and links -->
  <link rel="stylesheet" href="path/to/your/custom.css">
</head>
```

Step 4: Test and Refine

After applying your custom CSS, test your embedded Google Form to ensure that the styles are as you intended. You may need to make adjustments to the CSS as necessary to fine-tune the appearance and ensure it matches your website's theme.

Remember that the ability to customize the form's appearance through CSS is limited to the elements exposed by Google Forms. More advanced customizations might not be possible through CSS alone.

As a best practice, always test the form on various devices and browsers to ensure it looks good and functions well across different platforms.

Use this figma as a reference:

Screen Shot 2023-07-28 at 11 18 40 PM

### PR DESCRIPTION
**Pull request by KiloWattDot**
Issue Title: FD-007.3-GoogleAppStyling
Github #FD-007.3
Created by @KilowattDot

## Description
- Created the YNA Member application
- Couldn't get the Form to be attached to the Google Form due to it being an react act so we'll have to be build the backend for this
- Application features a scroll bar to cutdown on the length.
- Responsiveness designs applied

YNA member app

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`development`)
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

Release Notes
-------------

Decisions
---------

Technical Details
-----------------

Links
-----

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by Sydnee510 — COMMENTED** [review]
Missing git hub field, 
Radio buttons need their own ID - currently only able to have one radio button selected at a time, 
Be sure to use the present tense for the school field

**Review by Sydnee510 — COMMENTED** [review]
Also double check all your text box fields to make sure everything allows the user to type in
Fields to check: 
-current profession
-linked in profile
-shipping address

**Comment by KiloWattDot** [comment]
Fixed all errors. Please review.  @Young-N-Ambitious/frontend 


YNA member app - revised

**Comment by KiloWattDot** [comment]
@Sydnee510 @Young-N-Ambitious/frontend . My branch is up to date with the original. Please review once more.

**Review by Sydnee510 — APPROVED** [review]
QA/+1

**Review by bball07 — APPROVED** [review]
QA +1

**Pull request merged**
