### PR TITLE
FD-006.1-Build Contact Form

### LINKED ISSUE #113: FD-006.1-Customize styling for Google Contact Form

### PR DESCRIPTION
**Pull request by KiloWattDot**
I meant to make this branch off my forked repo but hopefully this is ok and doesn't cause any issues. 

contactform-PR

## Fixes

Fixes 
Issue Title: FD-###### - 
Github #[issue number]
Created by @[issue author]

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`development`)
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

Release Notes
-------------

Decisions
---------

Technical Details
-----------------

Links
-----

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by Sydnee510 — COMMENTED** [review]
hey the form looks great. let's resize the form and make it responsive @KiloWattDot

**Comment by KiloWattDot** [comment]
Hey the form is now responsive. I'm guessing by resize, you want the entire thing a little smaller? @Sydnee510

**Comment by Sydnee510** [comment]
Hey @KiloWattDot when I check the different mobile screens on my end, the form doesn't seem to be responsive. Check out my screenshots below after using the inspect tool in the browser. The bottom nav also seems to move from the bottom of the page on the mobile screens. Let me know if you want to hop on a call to clarify.

Screen Shot 2023-07-28 at 10 04 20 PM

Screen Shot 2023-07-28 at 10 04 03 PM

Screen Shot 2023-07-28 at 10 03 41 PM

Screen Shot 2023-07-28 at 10 03 29 PM

**Comment by KiloWattDot** [comment]
@Sydnee510. Hey check back over it when you get a chance. I think i fixed it.

**Comment by KiloWattDot** [comment]
My bad. I accidently hit close with comment :(

**Review by Sydnee510 — DISMISSED** [review]
QA/+1

**Review by DCTorres87 — APPROVED** [review]

**Review by Clue355 — CHANGES_REQUESTED** [review]
- The spacing above and below the contact form is too big and needs to be reduced
- The contact form itself looks a bit too small. please use the the width and height dimensions from the figma

**Comment by KiloWattDot** [comment]
Reduced the size but the spacing can't really be changed but if you see a way, you're  welcome to.

**Comment by Sydnee510** [comment]
looks like the placeholder text is different in the form boxes @KiloWattDot

**Comment by KiloWattDot** [comment]
My apologies, the placeholder font should match now. @Sydnee510

**Review by Sydnee510 — APPROVED** [review]
QA/+1

**Review by Clue355 — APPROVED** [review]

**Pull request merged**
